// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:test_app/pages/profile_page.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiL_xaIRKtdc3sPiLTHYfG7gHcUJ01Sz8',
    appId: '1:376829073240:web:dab168f8560ce0d557f72d',
    messagingSenderId: '376829073240',
    projectId: 'day2database',
    authDomain: 'day2database.firebaseapp.com',
    storageBucket: 'day2database.appspot.com',
    measurementId: 'G-1WG76T4477',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdNBUmIgtN-zKJs-Pape_3S-i46Q8MXTk',
    appId: '1:376829073240:android:8ed9847b5557815257f72d',
    messagingSenderId: '376829073240',
    projectId: 'day2database',
    storageBucket: 'day2database.appspot.com',
    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCctC7L1783zKFgnAO5kXtDxP7zvE4uyUI',
    appId: '1:376829073240:ios:b5b97be36226a1fb57f72d',
    messagingSenderId: '376829073240',
    projectId: 'day2database',
    storageBucket: 'day2database.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCctC7L1783zKFgnAO5kXtDxP7zvE4uyUI',
    appId: '1:376829073240:ios:b5b97be36226a1fb57f72d',
    messagingSenderId: '376829073240',
    projectId: 'day2database',
    storageBucket: 'day2database.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiL_xaIRKtdc3sPiLTHYfG7gHcUJ01Sz8',
    appId: '1:376829073240:web:51a1893ef6f38efb57f72d',
    messagingSenderId: '376829073240',
    projectId: 'day2database',
    authDomain: 'day2database.firebaseapp.com',
    storageBucket: 'day2database.appspot.com',
    measurementId: 'G-T0E5CHNVQS',
  );
}
